
server:
    name           :           "zaki el khadir"     
    host: 127.0.0.1
    port:   3000
    max_body_size :       1456

    error_pages:
      404: /home/saad/code/1337/webServer/assets/errors/404.html
      500: /home/saad/code/1337/webServer/assets/errors/50x.html
      302:  /home/saad/code/1337/webServer/assets/errors/302.html
    location :
      type : /
      directoryListing : on
      # root_directory: /root2
      root_directory: /home/zel-khad/Desktop/webServer/assets/authentification
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.html
      index  : index2.html

      # upload_dir :  hala madrid
    location :
      type : /zara
      directoryListing : off
      root_directory: /home/saad/code/1337/webServer/assets
      allowed_methods:
        - POST
        - DELETE

        #index  : index1.htm index1.html
      index  : page.html
    
    location :
      type : /upload
      directoryListing : on
      root_directory:  hala kkkkk              
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.html

    location :
      directoryListing : on
      type : uploadafvc a gv
      allowed_methods:
        - POST
        - DELETE
        - GET
      root_directory: /root              
      index  : index.htm

