
server:
    name           :           "zaki el khadir"     
    host: 127.0.0.1
    port:   3000
    port:   4000
    port:   5000
    port:   6000


    max_body_size :       1456

    error_pages:
      404: ./assets/errors/404.html
      500: ./assets/errors/50x.html
      302:  ./assets/errors/302.html
    location :
      type : /
      directoryListing : on
      root_directory: ./assets/web-folder/web
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.html
      index  : index2.html

    CGI:
      path :  ./cgi-bin/



server:
    name           :           "zaki el khadir"     
    host: 127.0.0.5
    port:   3000
    port:   4000
    port:   5000
    port:   6000


    max_body_size :       1456

    error_pages:
      404: ./assets/errors/404.html
      500: ./assets/errors/50x.html
      302:  ./assets/errors/302.html
  location :
      type : /
      directoryListing : on
      root_directory: ./assets/web-folder/web
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.html
      index  : index2.html

    CGI:
      path :  ./cgi-bin/
    
    location :
      type : /home
      directoryListing : on
      root_directory:  ./assets/home-folder/             
      allowed_methods:
        - POST
        # - DELETE
        - GET
      index  : index.html
      index  : index1.html
      

    location :
      type : /welcome
      allowed_methods:
        - POST
        - DELETE
        - GET
      root_directory: ./assets/welcome-folder/              
      index  : index.html
