
server :
  - id : name          
    name: name
    host: 0.0.0.78
    port:   8080
    max_body_size :       1

    error_pages:
      404: /errors/404.html
      403: /errors/403.html
      405:  /errors/405.html
      default: /errors/default.html

    location14 :
      type : /
      root_directory: iiiiiiiiiii
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.htm index.html
      upload_dir :  hala madrid
      
    location1 :
      type : zara
      root_directory: ooooooooooooo
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.htm index.html
      upload_dir :  hala madrid
    
    location2 :
      type : upload
      root_directory:  hala kkkkk              
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.htm index.html
      upload_dir : hala madrid
    location5 :
      type : upload
      root_directory:  hala llllllllllllll              
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.htm index.html
      upload_dir : hala madrid
