
server:
    name:           name
    host: 0.0.0.45
    port:   8080
    max_body_size :       1

    error_pages:
      410: /errors/404.html
      420: /errors/403.html
      300:  /errors/4045.html
      
    location :
      type : /
      root_directory: /root2
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index2.htm index2.html
      # upload_dir :  hala madrid
    location :
      type : zara
      root_directory: /root1
      allowed_methods:
        - POST

      index  : index1.htm index1.html
    
    location :
      type : upload
      root_directory:  hala kkkkk              
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.htm index.html

    location :
      type : upload
      allowed_methods:
        - POST
        - DELETE
        - GET
      root_directory: /root              
      index  : index.htm index.html

server :
    name:           name
    host: 0.0.0.45
    port:   8080
    max_body_size :       1

    error_pages:
      410: /errors/404.html
      420: /errors/403.html
      430:  /errors/4045.html


    location :
      type : /
      root_directory: /root2
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index2.htm index2.html
      # upload_dir :  hala madrid
      
    location :
      type : zara
      root_directory: /root1
      allowed_methods:
        - POST

      index  : index1.htm index1.html
    
    location :
      type : upload
      root_directory:  hala kkkkk              
      allowed_methods:
        - POST
        - DELETE
        - GET
      index  : index.htm index.html

    location :
      type : upload
      allowed_methods:
        - POST
        - DELETE
        - GET
      root_directory: /root              
      index  : index.htm index.html
