
server :
  - id : server1            
    name: my-web-server1
    host: 0.0.0               .0.0
    port:                 8080
    max_body_size : "50m"

    error_pages:
      404: /errors/404.html
      403: /errors/40.html
      405:  /errors/405.html
      default: /errors/default.html

    location / :
      root_directory: ""
      autoindex : off
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE

    location /upload :
      root_directory: ""
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
      index  : index.htm index.html
      max_body_size : 50m
      upload_dir : ""

  - id : server2            
    name: "my-web-   server"
    host: "0.0.0.0"
    port: "8080"
    max_body_size : "50m"

    error_pages:
      404: /errors/404.html
      403: /errors/40.html
      405:  /errors/405.html
      default: /errors/default.html

    location / :
      root_directory: ""
      autoindex : off
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE

    location /upload :
      root_directory: ""
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
      index  : index.htm index.html
      max_body_size : 50m
      upload_dir : ""
