
server :
  - id : name          
    name: name
    host: 0.0.0.78
    port:   8080
    max_body_size :       1

    error_pages:
      404: /errors/404.html
      403: /errors/403.html
      405:  /errors/405.html
      default: /errors/default.html

    location :
      type : "/" 
      root_directory: ""
      # allowed_methods:
      #   - GET
      #   - POST
      #   - PUT
      #   - DELETE

    location1 :
      type : zara
      root_directory: ""
      # allowed_methods:
      #   - GET
      #   - POST
      #   - PUT
      #   - DELETE
      index  : index.htm index.html
      upload_dir : "hala madrid"
    
    location2 :
      type : upload
      root_directory: "hala madrid"
      # allowed_methods:
      #   - GET
      #   - POST
      #   - PUT
      #   - DELETE
      index  : index.htm index.html
      upload_dir : "hala madrid"
